In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


data = pd.read_csv('ex1data2.csv')
print(data)


    population  number  profit
0         2104       3  399900
1         1600       3  329900
2         2400       3  369000
3         1416       2  232000
4         3000       4  539900
5         1985       4  299900
6         1534       3  314900
7         1427       3  198999
8         1380       3  212000
9         1494       3  242500
10        1940       4  239999
11        2000       3  347000
12        1890       3  329999
13        4478       5  699900
14        1268       3  259900
15        2300       4  449900
16        1320       2  299900
17        1236       3  199900
18        2609       4  499998
19        3031       4  599000
20        1767       3  252900
21        1888       2  255000
22        1604       3  242900
23        1962       4  259900
24        3890       3  573900
25        1100       3  249900
26        1458       3  464500
27        2526       3  469000
28        2200       3  475000
29        2637       3  299900
30        1839       2  349900
31      

### Columns to lists

In [6]:
population = list(data['population'])
number = list(data['number'])
profit = list(data['profit'])

### Defining X,y matrix

In [10]:
ones_1 = np.ones(len(population))



X = np.transpose(np.matrix([list(ones_1), population, number]))
y = np.transpose(np.matrix([profit[0:]]))

print(X)


[[1.000e+00 2.104e+03 3.000e+00]
 [1.000e+00 1.600e+03 3.000e+00]
 [1.000e+00 2.400e+03 3.000e+00]
 [1.000e+00 1.416e+03 2.000e+00]
 [1.000e+00 3.000e+03 4.000e+00]
 [1.000e+00 1.985e+03 4.000e+00]
 [1.000e+00 1.534e+03 3.000e+00]
 [1.000e+00 1.427e+03 3.000e+00]
 [1.000e+00 1.380e+03 3.000e+00]
 [1.000e+00 1.494e+03 3.000e+00]
 [1.000e+00 1.940e+03 4.000e+00]
 [1.000e+00 2.000e+03 3.000e+00]
 [1.000e+00 1.890e+03 3.000e+00]
 [1.000e+00 4.478e+03 5.000e+00]
 [1.000e+00 1.268e+03 3.000e+00]
 [1.000e+00 2.300e+03 4.000e+00]
 [1.000e+00 1.320e+03 2.000e+00]
 [1.000e+00 1.236e+03 3.000e+00]
 [1.000e+00 2.609e+03 4.000e+00]
 [1.000e+00 3.031e+03 4.000e+00]
 [1.000e+00 1.767e+03 3.000e+00]
 [1.000e+00 1.888e+03 2.000e+00]
 [1.000e+00 1.604e+03 3.000e+00]
 [1.000e+00 1.962e+03 4.000e+00]
 [1.000e+00 3.890e+03 3.000e+00]
 [1.000e+00 1.100e+03 3.000e+00]
 [1.000e+00 1.458e+03 3.000e+00]
 [1.000e+00 2.526e+03 3.000e+00]
 [1.000e+00 2.200e+03 3.000e+00]
 [1.000e+00 2.637e+03 3.000e+00]
 [1.000e+0

### With normal equation

In [11]:
def theta(X,y):
    theta = np.linalg.inv(np.transpose(X) * X) * np.transpose(X) * y
    return theta

print(theta(X,y))

[[89597.9095428 ]
 [  139.21067402]
 [-8738.01911233]]


### With Gradient descent

In [32]:
def J(X, y, theta):
    h = X * theta
    m = len(y)
    J = (np.sum((np.array(h - y))** 2))/(2 * m)
    return J

t0 = int(input("Introduce theta 0: "))
t1 = int(input("Introduce theta 1: "))
t2 = int(input("Introduce theta 1: "))
theta = np.transpose(np.matrix([t0,t1,t2]))

print(J(X,y,theta))
print(theta)


Introduce theta 0: 1
Introduce theta 1: 1
Introduce theta 1: 1
[[2108.]
 [1604.]
 [2404.]
 [1419.]
 [3005.]
 [1990.]
 [1538.]
 [1431.]
 [1384.]
 [1498.]
 [1945.]
 [2004.]
 [1894.]
 [4484.]
 [1272.]
 [2305.]
 [1323.]
 [1240.]
 [2614.]
 [3036.]
 [1771.]
 [1891.]
 [1608.]
 [1967.]
 [3894.]
 [1104.]
 [1462.]
 [2530.]
 [2204.]
 [2641.]
 [1842.]
 [1002.]
 [2045.]
 [3141.]
 [1816.]
 [1441.]
 [1243.]
 [2137.]
 [4220.]
 [2167.]
 [1667.]
 [2242.]
 [2572.]
 [1204.]
 [ 855.]
 [1857.]
 [1207.]]
64828197300.797874
[[1]
 [1]
 [1]]


In [36]:
iterations = int(input("Introduce el número de iteraciones: "))
alpha = float(input("Introduce el parámetro alpha: "))


def grad_desc(X, y, theta, alpha, iterations):
    m = len(y)
    thet = theta
    for i in range(iterations):
        h = X * thet
        z= (np.transpose(X) * (h - y))/ m
       # print(thet-alpha * z)
        print(np.transpose(X) * (h - y))
        thet = thet -alpha * z
    return thet

thet_1 = grad_desc(X,y, theta, alpha, iterations)
print(thet_1)


Introduce el número de iteraciones: 4
Introduce el parámetro alpha: 0.1
[[-1.59051670e+07]
 [-3.57002419e+10]
 [-5.23429550e+07]]
[[7.14248132e+12]
 [1.64965074e+16]
 [2.38264257e+13]]
[[-3.30042577e+18]
 [-7.62277035e+21]
 [-1.10098079e+19]]
[[1.52507359e+24]
 [3.52235940e+27]
 [5.08745488e+24]]
[[-3.24483040e+21]
 [-7.49436548e+24]
 [-1.08243487e+22]]
